C
C********************************************************************
C
      SUBROUTINE FECHK
      CHARACTER*20 LOGFIL
      INTEGER*4 MONOUT,LENFIL,ISTREC,MNCUR, LOGGED
      INTEGER*4 ERROUT
      COMMON/CFELIB/MONOUT,LOGGED,LENFIL,ISTREC,MNCUR,
     *              LOGFIL
C
      DATA ERROUT /1/
C
C     CHECK IF FEINIT HAS BEEN CALLED
C
      IF(LOGGED.EQ.9999) RETURN
C
C     CHECK IF FEFIN HAS BEEN CALLED BEFORE END
C
      IF(LOGGED.EQ.7777) THEN
         WRITE(ERROUT,9020)
      ELSE
C
C     FEINIT EITHER NOT INCLUDED OR CALLED TO LATE
C
         LOGGED=8888
         CALL FEINIT
         WRITE(ERROUT,9010)
      ENDIF
      STOP
 9010 FORMAT('ERROR DETECTED - FEINIT SHOULD BE THE FIRST'
     *       ' EXECUTABLE STATEMENT IN THE PROGRAM')
 9020 FORMAT('ERROR DETECTED - FEFIN SHOULD BE THE LAST'
     *       ' EXECUTABLE STATEMENT IN THE PROGRAM')
      END
