      DOUBLE PRECISION FUNCTION GENSOL(TIME, P, DAMPR, EIGVAL,
     *     AMP, OMEGA)
      DOUBLE PRECISION AMP, COEF1, COEF2, DAMPR, DENOM, EIGVAL,
     *     OMEGA, P, TIME
      DENOM = (EIGVAL-OMEGA**2)**2 + 4.0D0*DAMPR**2*OMEGA**2*EIGVAL
      COEF1 = P*(EIGVAL-OMEGA**2)/DENOM
      COEF2 = P*2.0D0*OMEGA*DSQRT(EIGVAL)*DAMPR/DENOM
      GENSOL = COEF1*DCOS(OMEGA*TIME) + COEF2*DSIN(OMEGA*TIME)
      RETURN
      END
