C
C********************************************************************
C
      SUBROUTINE FEINIT
      DOUBLE PRECISION FELIB
      CHARACTER*20 LOGFIL
      INTEGER*4 ERROUT
      INTEGER*4 MONOUT,LENFIL,ISTREC,MNCUR, LOGGED
      COMMON/CFELIB/MONOUT,LOGGED,LENFIL,ISTREC,MNCUR,
     *              LOGFIL
C
      DATA ERROUT /1/
      DATA FELIB /8HFELIB   /
C
C     CHECK IF ONLY TEST
C
      IF(LOGGED.EQ.8888) RETURN
C
C     NOT TEST - THE REAL THING
C
C     CHECK ON FEFIN
C
      LOGGED=6666
      CALL FEFIN
C
C     FEFIN OK - CONTINUE - SET FLAG ETC.
C
      LOGGED=9999
      MONOUT=10
      LENFIL=32
      ISTREC=1
      LOGFIL='ENGSFT>LOG>DATAFILE'
      CALL MNSTRT(MONOUT,ERROUT,LOGFIL,FELIB,LENFIL,
     *            ISTREC,MNCUR)
      RETURN
      END
