C
      DOUBLE PRECISION FUNCTION SOURCE(X, Y, STRGTH)
      DOUBLE PRECISION STRGTH, X, Y
      SOURCE = 0.0D0
      IF ((X.GE.1.0D0) .AND. (X.LE.2.0D0) .AND. (Y.GE.1.0D0) .AND.
     *     (Y.LE.2.0D0)) SOURCE = STRGTH
      RETURN
      END
