      SUBROUTINE MESH(COORD,ICOORD,NOD)
      REAL COORD(ICOORD,2)
      CALL POINT(COORD(1,1),COORD(1,2))
      J=NOD+1
      DO 1 I=1,NOD
      K=J-I
    1 CALL JOIN(COORD(K,1),COORD(K,2))
      RETURN
      END
      SUBROUTINE A4WIDE(X1,X2,Y1,Y2)
      CALL PSPACE(.31,1.30,.25,.95)
      CALL MAP(X1,X2,Y1,Y2)
      CALL BORDER
      RETURN
      END
      SUBROUTINE A4TALL (X1,X2,Y1,Y2)
      CALL PSPACE(.1,.8,.01,1.)
      CALL MAP(X1,X2,Y1,Y2)
      CALL BORDER
      RETURN
      END
